apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-svc
  name: my-svc
  namespace: default
spec:
  clusterIP: 10.100.35.31
  clusterIPs:
  - 10.100.35.31
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-80
    nodePort: 31852
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: my-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
