name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main # oder Ihren Hauptbranch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set KUBECONFIG Environment Variable
      run: echo "KUBECONFIG=${{ secrets.KUBECONFIG_PATH }}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0' # Nutzen Sie die gewünschte Kubectl-Version

    - name: Set up DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

