on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Create namespace
        run: kubectl create namespace djandthebitches --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          namespace: 'djandthebitches'
          secret-name: 'regcred'
          container-registry-url: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        id: create-secret
