name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main # Oder den Branch, den Sie verwenden möchten

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up Kubernetes configuration
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: do-fra1-k8s-1-29-1-do-0-fra1-1709714425576

      # Deployment
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml

